window.FVK=window.FVK||{};
FVK.Engine=(()=>{
const L=['approach','breach','district2','district1','cityCore'];let s=null,subs=[];
const inward=x=>L[Math.min(L.indexOf(x)+1,4)],outward=x=>L[Math.max(L.indexOf(x)-1,0)],adj=(a,b)=>Math.abs(L.indexOf(a)-L.indexOf(b))===1;
const card=id=>FVK.DATA.kaijuCards.find(x=>x.id===id)||FVK.DATA.washingtonCards.find(x=>x.id===id),district=id=>FVK.DATA.districts.find(x=>x.id===id);
function emit(){subs.forEach(f=>f(s))} function subscribe(f){subs.push(f)} function log(type,msg,data={}){s.log.push({exchange:s.exchange,phase:s.phase,type,message:msg,...data})}
function rng(seed){let h=2166136261;for(const c of seed)h=Math.imul(h^c.charCodeAt(0),16777619);return()=>{h+=0x6D2B79F5;let t=h;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function shuffle(a,r){a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function start(seed='FVSK-'+Math.floor(Date.now()/1000)){let r=rng(seed),rev=shuffle(FVK.DATA.districts.map(x=>x.id),r).slice(0,3);s={seed,exchange:1,phase:'setup_washington_district',winner:null,setup:{revealed:rev,d1:null,d2:null},kaiju:{dormant:true,health:null,location:'approach',hand:[],deck:shuffle(FVK.DATA.kaijuCards.map(x=>x.id),r),discard:[],evolutions:{head:null,body:null,tail:null}},washington:{location:'district1',hand:[],deck:shuffle(FVK.DATA.washingtonCards.map(x=>x.id),r),discard:[],actions:0},battlefield:{approach:{label:'Approach',state:'fixed',forts:[]},breach:{label:'Breach',state:'fixed',forts:[]},district2:{label:'District II',state:'fortified',forts:[],districtId:null},district1:{label:'District I',state:'fortified',forts:[],districtId:null},cityCore:{label:'City Core',state:'fixed',forts:[],coreBreached:false}},waves:{supply:['Wave 1','Wave 2','Wave 3'],active:[],destroyed:[]},pending:null,choice:null,finalResponse:false,log:[],metrics:{awakening:null,healthByEntry:{breach:null,district2:null,district1:null,cityCore:null},routes:{force:0,adapt:0,overrun:0},strikes:0,evolutions:0,wavesBreached:0}};log('setup','Game created with seed '+seed);emit();return s}
function chooseDistrict(id){if(!s.setup.revealed.includes(id))return;if(s.phase==='setup_washington_district'){s.setup.d1=id;s.battlefield.district1.districtId=id;s.phase='setup_kaiju_district';log('setup','Washington chose '+district(id).name+' for District I')}else if(s.phase==='setup_kaiju_district'&&id!==s.setup.d1){s.setup.d2=id;s.battlefield.district2.districtId=id;draw('kaiju',FVK.CONFIG.kaijuStartingHand);draw('washington',FVK.CONFIG.washingtonStartingHand);s.phase='kaiju_act';log('setup','Kaiju chose '+district(id).name+' for District II')}emit()}
function draw(who,n=1){let p=s[who];for(let i=0;i<n&&p.deck.length;i++)p.hand.push(p.deck.shift());limit(who)}
function limit(who){let p=s[who],max=who==='kaiju'?FVK.CONFIG.kaijuHandLimit:FVK.CONFIG.washingtonHandLimit;if(p.hand.length>max)s.choice={kind:'discardLimit',who,count:p.hand.length-max,prompt:'Discard '+(p.hand.length-max)+' card(s) to hand limit.'}}
function discard(who,id){let p=s[who],i=p.hand.indexOf(id);if(i>=0){p.hand.splice(i,1);p.discard.push(id)}}
function canAwaken(){return s.kaiju.dormant&&s.kaiju.hand.filter(id=>(card(id).tags||[]).includes('TIDE')).length>=FVK.CONFIG.awakeningTideCost}
function awaken(ids){if(!ids){s.choice={kind:'multi',who:'kaiju',count:2,ids:s.kaiju.hand.filter(id=>(card(id).tags||[]).includes('TIDE')),purpose:'awaken',prompt:'Choose 2 TIDE cards to Awaken.'};emit();return}ids.forEach(id=>discard('kaiju',id));s.choice=null;s.kaiju.dormant=false;s.kaiju.health=FVK.CONFIG.kaijuHealth;s.metrics.awakening=s.exchange;createWave();draw('kaiju',1);log('awaken','Colossus Rex Awakens.');toWashington();emit()}
function toWashington(){s.phase='washington_response';s.washington.actions=FVK.CONFIG.washingtonActions}
function endWashingtonAction(){s.washington.actions--;if(s.winner)return;if(s.washington.actions<=0){if(s.finalResponse){if(s.kaiju.health>0){s.winner='kaiju';s.phase='game_over';log('victory','Kaiju survives the final Response.')}}else{draw('washington',1);if(!s.choice)s.phase='kaiju_adapt'}}}
function endKaijuAct(){toWashington();emit()} function endAdapt(){s.exchange++;s.phase='kaiju_act';emit()}
function damage(n,src){if(s.kaiju.dormant||s.kaiju.location==='approach')return;s.kaiju.health-=n;log('damage',src+' deals '+n+' Health.');if(s.kaiju.health<=0){s.kaiju.health=0;s.winner='washington';s.phase='game_over';log('victory','Washington wins.')}}
function baseGate(loc){if(loc==='breach')return{force:2,adapt:2};if(loc==='cityCore')return{force:3,adapt:3};return {...district(s.battlefield[loc].districtId).gate}}
function gate(loc){let g=baseGate(loc),a=s.battlefield[loc];if((loc==='district1'||loc==='district2')&&a.state==='breached'){g.force=Math.max(1,g.force-1);g.adapt=Math.max(1,g.adapt-1)}if(a.state==='ruined')g={force:0,adapt:0};if(loc==='breach'&&s.waves.active.some(w=>w.location==='breach')){g.force=Math.max(1,g.force-1);g.adapt=Math.max(1,g.adapt-1)}if(loc==='cityCore'&&a.coreBreached){g.force=Math.max(1,g.force-1);g.adapt=Math.max(1,g.adapt-1)}for(const id of a.forts){if(id==='W01')g.force++;if(id==='W02'){g.force=Math.max(1,g.force-1);g.adapt++}if(id==='W06'){g.adapt=Math.max(1,g.adapt-1);g.force++}}if(s.kaiju.evolutions.head==='K13')g.force=Math.max(1,g.force-1);return g}
function startAdvance(){if(s.kaiju.dormant||s.kaiju.location==='cityCore')return;s.pending={next:inward(s.kaiju.location),route:null,cards:[],carapace:null};emit()} function cancelAdvance(){s.pending=null;emit()}
function chooseRoute(r){s.pending.route=r;s.pending.cards=[];emit()} function togglePay(id){let a=s.pending.cards,i=a.indexOf(id);i>=0?a.splice(i,1):a.push(id);emit()}
function summary(){if(!s.pending||!s.pending.route)return null;let r=s.pending.route,need=gate(s.pending.next)[r],got=0;for(const id of s.pending.cards){let c=card(id);got+=id==='K09'?1:(c.gate[r]||0)}let miss=Math.max(0,need-got),car=s.kaiju.evolutions.body==='K17'&&s.pending.carapace&&miss>0?1:0;return{required:need,symbols:got,missing:miss,healthCost:miss-car}}
function setCarapace(id){s.pending.carapace=s.pending.carapace===id?null:id;emit()}
function confirmAdvance(){let p=s.pending,x=summary();if(!p||!x)return;p.cards.forEach(id=>discard('kaiju',id));if(p.carapace)discard('kaiju',p.carapace);s.metrics.routes[p.route]++;s.metrics.routes.overrun+=x.healthCost;if(x.healthCost)damage(x.healthCost,'Overrun');if(s.winner){s.pending=null;emit();return}let from=s.kaiju.location;s.kaiju.location=p.next;if(s.metrics.healthByEntry[p.next]==null)s.metrics.healthByEntry[p.next]=s.kaiju.health;log('advance','Colossus '+from+' → '+p.next+' via '+p.route.toUpperCase()+'.');resolveEntry(p.next,p.route);s.pending=null;if(!s.winner){if(p.next==='cityCore'){s.finalResponse=true;toWashington();log('final','Final Response begins.')}else endKaijuAct()}emit()}
function deteriorate(loc,body=true){let a=s.battlefield[loc];if(!['district1','district2'].includes(loc))return;if(a.state==='fortified'){a.state='breached';while(a.forts.length>1){let id=a.forts.pop();s.washington.discard.push(id)}log('district',a.label+' becomes Breached.')}else if(a.state==='breached'&&body){a.state='ruined';a.forts.splice(0).forEach(id=>s.washington.discard.push(id));log('district',a.label+' becomes Ruined.')}}
function resolveEntry(loc,route){let a=s.battlefield[loc];if(['district1','district2'].includes(loc)){let d=a.districtId;if(d==='D01'&&route==='force')damage(1,'Harbor Batteries');if(a.forts.includes('W03')&&route==='force')damage(1,'Coastal Battery');if(a.forts.includes('W11')&&(s.washington.location===loc||adj(s.washington.location,loc)))damage(1,'Continental Volley');deteriorate(loc,true)}moveWaves();createWave()}
function createWave(){if(!s.waves.supply.length)return;let name=s.waves.supply.shift();s.waves.active.push({name,location:'breach'});log('wave',name+' enters Breach.')}
function moveWaves(){let arr=[...s.waves.active].sort((a,b)=>L.indexOf(b.location)-L.indexOf(a.location));for(const w of arr){w.location=inward(w.location);log('wave',w.name+' moves to '+w.location+'.');if(['district1','district2'].includes(w.location)){let a=s.battlefield[w.location];if(a.state==='fortified'){a.state='breached';s.metrics.wavesBreached++;while(a.forts.length>1){let id=a.forts.pop();s.washington.discard.push(id)}log('wave',w.name+' Breaches '+a.label+'.')}}else if(w.location==='cityCore'){let a=s.battlefield.cityCore;if(!a.coreBreached)a.coreBreached=true;else if(a.forts.length)s.washington.discard.push(a.forts.pop());s.waves.active=s.waves.active.filter(x=>x!==w);s.waves.destroyed.push(w.name);log('wave',w.name+' impacts City Core and leaves play.')}}}
function capacity(loc){let a=s.battlefield[loc];if(loc==='approach')return 0;if(loc==='breach'||loc==='cityCore')return 1;return a.state==='fortified'?2:a.state==='breached'?1:0}
function playKaiju(id,mode){if(s.phase!=='kaiju_act')return;let c=card(id);discard('kaiju',id);log('kaiju_card',c.name+' used as '+mode+'.');if(mode==='manifest'){if(c.id==='K07'||c.id==='K14')moveWaves();if(c.id==='K17'&&Object.values(s.kaiju.evolutions).some(Boolean)){let slot=['head','body','tail'].find(k=>s.kaiju.evolutions[k]);s.kaiju.discard.push(s.kaiju.evolutions[slot]);s.kaiju.evolutions[slot]=null;s.kaiju.health=Math.min(FVK.CONFIG.kaijuHealth,s.kaiju.health+1)}}if(mode==='instinct')draw('kaiju',1);endKaijuAct()}
function adaptDraw(){if(s.phase!=='kaiju_adapt')return;draw('kaiju',1);if(!s.choice)endAdapt()} function evolve(id){if(s.phase!=='kaiju_adapt'||s.kaiju.dormant)return;let c=card(id);if(!c.evolution)return;discard('kaiju',id);let old=s.kaiju.evolutions[c.evolution.slot];if(old)s.kaiju.discard.push(old);s.kaiju.evolutions[c.evolution.slot]=id;s.metrics.evolutions++;log('evolution',c.name+' installed in '+c.evolution.slot+'.');endAdapt()}
function canStrike(){if(s.kaiju.dormant||s.kaiju.location==='approach')return false;let k=s.kaiju.location,w=s.washington.location;if(k==='breach')return w==='breach';if(k==='district2')return ['district2','district1'].includes(w);if(k==='district1')return ['district2','district1','cityCore'].includes(w);return ['district1','cityCore'].includes(w)}
function strike(){if(s.phase!=='washington_response'||!canStrike())return;let prior=s.log.filter(e=>e.exchange===s.exchange&&e.type==='strike').length;if(!s.finalResponse&&prior>=1)return;let dmg=1;if(s.battlefield[s.washington.location].forts.includes('W15')){dmg++;let a=s.battlefield[s.washington.location],i=a.forts.indexOf('W15');a.forts.splice(i,1);s.washington.discard.push('W15')}s.metrics.strikes++;log('strike','Washington Strikes for '+dmg+'.');damage(dmg,'Strike');if(!s.winner)endWashingtonAction();emit()}
function moveWashington(dir){if(s.phase!=='washington_response')return;let d=dir==='inward'?inward(s.washington.location):outward(s.washington.location);if(d==='approach'||d===s.washington.location)return;s.washington.location=d;log('move','Washington moves to '+d+'.');endWashingtonAction();emit()}
function rally(){if(s.phase!=='washington_response'||!s.washington.deck.length)return;let n=s.battlefield[s.washington.location].forts.includes('W14')?3:2,look=s.washington.deck.splice(0,n);s.choice={kind:'pick',who:'washington',ids:look,purpose:'rally',prompt:'Choose 1 Rally card to keep.'};emit()}
function playWashington(id,mode){if(s.phase!=='washington_response')return;let c=card(id);if(mode==='fortify'){let a=s.battlefield[s.washington.location],cap=capacity(s.washington.location);if(!cap)return;let shaper=c.fortify.gateShaper;if(shaper&&a.forts.some(x=>card(x).fortify.gateShaper))return;if(a.forts.length>=cap){let old=a.forts.shift();s.washington.discard.push(old)}discard('washington',id);s.washington.discard.pop();a.forts.push(id);log('fortify',c.name+' Fortifies '+a.label+'.')}else{discard('washington',id);log('command',c.name+' Command.');if(['W03','W11'].includes(id)&&!s.kaiju.dormant&&s.kaiju.location!=='approach'&&(s.kaiju.location===s.washington.location||adj(s.kaiju.location,s.washington.location)))damage(1,c.name);if(['W02','W10'].includes(id)&&['district1','district2'].includes(s.washington.location)&&s.battlefield[s.washington.location].state==='breached')s.battlefield[s.washington.location].state='fortified';if(id==='W15')draw('washington',2)}if(!s.winner)endWashingtonAction();emit()}
function resolveChoice(v){let c=s.choice;if(!c)return;if(c.kind==='multi'){if(c.purpose==='awaken')return awaken(v)}if(c.kind==='discardLimit'){for(const id of v)discard(c.who,id);s.choice=null;emit();return}if(c.kind==='pick'&&c.purpose==='rally'){let rest=c.ids.filter(x=>x!==v);s.washington.hand.push(v);s.washington.deck.push(...rest);s.choice=null;limit('washington');if(!s.choice)endWashingtonAction();emit()}}
function exportJSON(){return JSON.stringify({state:s,summary:getSummary()},null,2)} function getSummary(){return{winner:s.winner,exchange:s.exchange,seed:s.seed,awakening:s.metrics.awakening,healthByEntry:s.metrics.healthByEntry,routes:s.metrics.routes,strikes:s.metrics.strikes,evolutions:s.metrics.evolutions,wavesBreached:s.metrics.wavesBreached}}
function debug(action,p={}){if(action==='health')s.kaiju.health=+p.value;if(action==='kaijuLocation')s.kaiju.location=p.value;if(action==='washingtonLocation')s.washington.location=p.value;if(action==='addWave')createWave();emit()}
return{L,start,subscribe,getState:()=>s,chooseDistrict,card,district,gate,capacity,canAwaken,awaken,playKaiju,startAdvance,cancelAdvance,chooseRoute,togglePay,setCarapace,summary,confirmAdvance,adaptDraw,evolve,canStrike,strike,moveWashington,rally,playWashington,resolveChoice,exportJSON,getSummary,debug}
})();