window.FVK=window.FVK||{};
FVK.UI=(()=>{
const $=q=>document.querySelector(q),E=FVK.Engine;let overlay,modal;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const name=id=>{let c=E.card(id);return c?c.id+' — '+c.name:id};
function init(){overlay=$('#overlay');modal=$('#modal')}
function button(t,fn,disabled=false,title=''){let b=document.createElement('button');b.textContent=t;b.disabled=disabled;b.title=title;b.onclick=fn;return b}
function phaseName(p){return({setup_washington_district:'Setup — Washington',setup_kaiju_district:'Setup — Kaiju',kaiju_act:'Kaiju Act',washington_response:'Washington Response',kaiju_adapt:'Kaiju Adapt',game_over:'Game Over'})[p]||p}
function render(s){if(!s)return;renderStatus(s);renderBattlefield(s);renderPlayers(s);renderLog(s);renderDev(s);renderModal(s)}
function renderStatus(s){$('#statusStrip').innerHTML=[`Exchange ${s.exchange}`,phaseName(s.phase),`Seed ${s.seed}`].map(x=>`<span class="pill">${esc(x)}</span>`).join('')}
function renderBattlefield(s){let root=$('#battlefield');root.innerHTML='';for(const loc of E.L){let a=s.battlefield[loc],d=a.districtId?E.district(a.districtId):null,g=(loc==='approach'||a.state==='ruined')?null:E.gate(loc),waves=s.waves.active.filter(w=>w.location===loc),el=document.createElement('div');el.className='area '+(s.kaiju.location===loc?'kaiju-here ':'')+(s.washington.location===loc?'washington-here':'');el.innerHTML=`<div class="area-title"><div><h3>${esc(a.label)}</h3>${d?`<div class="district-name">${esc(d.name)}</div>`:''}</div><span class="state ${a.state}">${esc(a.state.toUpperCase())}</span></div>${g?`<div class="gate"><div>FORCE<strong>${g.force}</strong></div><div>ADAPT<strong>${g.adapt}</strong></div></div>`:'<div class="gate"><div>NO GATE</div><div>—</div></div>'}<div class="area-tokens">${s.kaiju.location===loc?`<span class="token kaiju">COLOSSUS ${s.kaiju.dormant?'DORMANT':s.kaiju.health+' HP'}</span>`:''}${s.washington.location===loc?'<span class="token wash">WASHINGTON</span>':''}${waves.map(w=>`<span class="token wave">${esc(w.name)}</span>`).join('')}</div><div class="fort-list">${a.forts.map(id=>`<div class="fort">${esc(name(id))}</div>`).join('')}</div>${d?`<div class="area-ability">${esc(d.ability)}</div>`:''}${loc==='cityCore'&&a.coreBreached?'<div class="area-ability">CORE BREACHED — Gate -1</div>':''}`;root.appendChild(el)}}
function symbols(c){if(!c.gate)return'';if(c.gate.flex)return'<span class="symbol">FORCE / ADAPT</span>';let x='';for(let i=0;i<(c.gate.force||0);i++)x+='<span class="symbol">FORCE</span>';for(let i=0;i<(c.gate.adapt||0);i++)x+='<span class="symbol">ADAPT</span>';return x}
function renderPlayers(s){$('#kaijuStats').innerHTML=`<span class="pill">${s.kaiju.dormant?'DORMANT':s.kaiju.health+' HP'}</span><span class="pill">Deck ${s.kaiju.deck.length}</span><span class="pill">Discard ${s.kaiju.discard.length}</span>`;$('#washingtonStats').innerHTML=`<span class="pill">Actions ${s.phase==='washington_response'?s.washington.actions:'—'}</span><span class="pill">Deck ${s.washington.deck.length}</span><span class="pill">Discard ${s.washington.discard.length}</span>`;renderEvos(s);renderKaijuActions(s);renderWashActions(s);renderHand('#kaijuHand',s.kaiju.hand,'kaiju',s);renderHand('#washingtonHand',s.washington.hand,'washington',s)}
function renderEvos(s){$('#evolutions').innerHTML=['head','body','tail'].map(slot=>{let id=s.kaiju.evolutions[slot];return`<div class="evo-slot"><div class="slot-label">${slot.toUpperCase()}</div>${id?`<strong>${esc(name(id))}</strong><div class="district-name">${esc(E.card(id).evolution.text)}</div>`:'<span class="district-name">Empty</span>'}</div>`}).join('')}
function renderKaijuActions(s){let a=$('#kaijuActions');a.innerHTML='';a.appendChild(spanPill(s.phase==='kaiju_act'?'Choose one Kaiju Act':s.phase==='kaiju_adapt'?'Adapt: Draw or Evolve':'Waiting'));if(s.phase==='kaiju_act'){if(s.kaiju.dormant)a.appendChild(button('Awaken',()=>E.awaken(),!E.canAwaken(),'Need 2 TIDE cards'));else if(s.kaiju.location!=='cityCore')a.appendChild(button('Advance',()=>E.startAdvance()))}if(s.phase==='kaiju_adapt')a.appendChild(button('Draw 1',()=>E.adaptDraw()))}
function renderWashActions(s){let a=$('#washingtonActions');a.innerHTML='';if(s.phase!=='washington_response'){a.appendChild(spanPill('Waiting'));return}a.appendChild(button('Move ←',()=>E.moveWashington('outward'),s.washington.location==='breach'));a.appendChild(button('Move →',()=>E.moveWashington('inward'),s.washington.location==='cityCore'));a.appendChild(button('Strike',()=>E.strike(),!E.canStrike(),'No legal firing position'));a.appendChild(button('Rally',()=>E.rally(),!s.washington.deck.length,'Deck empty'))}
function spanPill(t){let x=document.createElement('span');x.className='pill';x.textContent=t;return x}
function renderHand(sel,ids,who,s){let root=$(sel);root.innerHTML='';for(const id of ids)root.appendChild(makeCard(id,who,s))}
function makeCard(id,who,s){let c=E.card(id),n=$('#cardTemplate').content.firstElementChild.cloneNode(true);n.querySelector('.card-id').textContent=c.id;n.querySelector('.card-tag').textContent=(c.tags||[]).join(' · ');n.querySelector('.card-name').textContent=c.name;n.querySelector('.card-symbols').innerHTML=who==='kaiju'?symbols(c):'';let copy=n.querySelector('.card-copy'),actions=n.querySelector('.card-buttons');if(who==='kaiju'){copy.innerHTML=(c.instinct?`<div class="copy-row"><strong>INSTINCT</strong> ${esc(c.instinct)}</div>`:'')+(c.manifest?`<div class="copy-row"><strong>MANIFEST</strong> ${esc(c.manifest)}</div>`:'')+(c.evolution?`<div class="copy-row"><strong>EVOLVE · ${c.evolution.slot.toUpperCase()}</strong> ${esc(c.evolution.text)}</div>`:'');if(s.phase==='kaiju_act'){actions.appendChild(button('Instinct',()=>E.playKaiju(id,'instinct')));if(c.manifest)actions.appendChild(button('Manifest',()=>E.playKaiju(id,'manifest'),s.kaiju.dormant&&c.manifest.startsWith('Awakened')))}if(s.phase==='kaiju_adapt'&&!s.kaiju.dormant&&c.evolution)actions.appendChild(button('Evolve',()=>E.evolve(id)))}else{copy.innerHTML=`<div class="copy-row"><strong>COMMAND</strong> ${esc(c.command)}</div><div class="copy-row"><strong>FORTIFY · ${esc(c.fortify.type)}</strong> ${esc(c.fortify.text)}</div>`;if(s.phase==='washington_response'){actions.appendChild(button('Command',()=>E.playWashington(id,'command')));actions.appendChild(button('Fortify',()=>E.playWashington(id,'fortify')))}}return n}
function renderLog(s){$('#log').innerHTML=s.log.slice().reverse().map(e=>`<div class="log-row"><span>E${e.exchange} · ${esc(e.type.toUpperCase())}</span>${esc(e.message)}</div>`).join('')}
function open(html){modal.innerHTML=html;overlay.classList.remove('hidden')} function close(){overlay.classList.add('hidden');modal.innerHTML=''}
function renderModal(s){if(s.phase==='game_over')return report(s);if(s.phase.startsWith('setup_'))return setupModal(s);if(s.pending)return advanceModal(s);if(s.choice)return choiceModal(s);close()}
function setupModal(s){let who=s.phase==='setup_washington_district'?'Washington':'Kaiju',ids=s.setup.revealed.filter(id=>id!==s.setup.d1);open(`<div class="eyebrow">SETUP</div><h2>${who}: choose ${who==='Washington'?'District I':'District II'}</h2><div class="choice-grid">${ids.map(id=>{let d=E.district(id);return`<button class="choice-card setup" data-id="${id}"><strong>${esc(d.id+' — '+d.name)}</strong><div>FORCE ${d.gate.force} / ADAPT ${d.gate.adapt}</div><small>${esc(d.ability)}</small></button>`}).join('')}</div>`);modal.querySelectorAll('.setup').forEach(b=>b.onclick=()=>E.chooseDistrict(b.dataset.id))}
function advanceModal(s){let p=s.pending,g=E.gate(p.next),sum=E.summary(),html=`<div class="eyebrow">ADVANCE</div><h2>Enter ${esc(s.battlefield[p.next].label)}</h2><p>Choose Force or Adapt, then select payment cards. Missing requirements cost Health through Overrun.</p><div class="action-row"><button id="rf">FORCE ${g.force}</button><button id="ra">ADAPT ${g.adapt}</button></div>`;if(p.route){html+=`<div class="advance-summary"><div>Required<strong>${sum.required}</strong></div><div>Symbols<strong>${sum.symbols}</strong></div><div>Missing<strong>${sum.missing}</strong></div><div>Health Cost<strong>${sum.healthCost}</strong></div></div><div class="choice-grid">${s.kaiju.hand.map(id=>{let c=E.card(id),sel=p.cards.includes(id),car=p.carapace===id;return`<div class="choice-card ${sel?'selected':''}"><strong>${esc(name(id))}</strong><div>${symbols(c)}</div><div class="modal-actions"><button class="pay" data-id="${id}">${sel?'Remove':'Pay'}</button>${s.kaiju.evolutions.body==='K17'&&!sel?`<button class="car secondary" data-id="${id}">${car?'Carapace ✓':'Carapace discard'}</button>`:''}</div></div>`}).join('')}</div><div class="modal-actions"><button id="cancel" class="secondary">Cancel</button><button id="confirm" class="${sum.healthCost>=s.kaiju.health?'danger':''}">Confirm Advance</button></div>`}else html+='<div class="modal-actions"><button id="cancel" class="secondary">Cancel</button></div>';open(html);$('#rf').onclick=()=>E.chooseRoute('force');$('#ra').onclick=()=>E.chooseRoute('adapt');modal.querySelectorAll('.pay').forEach(b=>b.onclick=()=>E.togglePay(b.dataset.id));modal.querySelectorAll('.car').forEach(b=>b.onclick=()=>E.setCarapace(b.dataset.id));if($('#confirm'))$('#confirm').onclick=()=>E.confirmAdvance();$('#cancel').onclick=()=>E.cancelAdvance()}
function choiceModal(s){let c=s.choice;if(c.kind==='multi'||c.kind==='discardLimit'){let ids=c.ids||s[c.who].hand;open(`<div class="eyebrow">${esc(c.who.toUpperCase())} CHOICE</div><h2>${esc(c.prompt)}</h2><div class="choice-grid">${ids.map(id=>`<button class="choice-card multi" data-id="${id}"><strong>${esc(name(id))}</strong></button>`).join('')}</div><div class="modal-actions"><span id="mc" class="pill">0 / ${c.count}</span><button id="mconfirm" disabled>Confirm</button></div>`);let set=new Set;modal.querySelectorAll('.multi').forEach(b=>b.onclick=()=>{let id=b.dataset.id;if(set.has(id)){set.delete(id);b.classList.remove('selected')}else if(set.size<c.count){set.add(id);b.classList.add('selected')}$('#mc').textContent=set.size+' / '+c.count;$('#mconfirm').disabled=set.size!==c.count});$('#mconfirm').onclick=()=>E.resolveChoice([...set]);return}if(c.kind==='pick'){open(`<div class="eyebrow">${esc(c.who.toUpperCase())} CHOICE</div><h2>${esc(c.prompt)}</h2><div class="choice-grid">${c.ids.map(id=>`<button class="choice-card pick" data-id="${id}"><strong>${esc(name(id))}</strong></button>`).join('')}</div>`);modal.querySelectorAll('.pick').forEach(b=>b.onclick=()=>E.resolveChoice(b.dataset.id))}}
function report(s){let x=E.getSummary();open(`<div class="eyebrow">GAME OVER</div><h2>${x.winner==='kaiju'?'KAIJU VICTORY':'WASHINGTON VICTORY'}</h2><div class="report-grid"><div class="report-box"><h3>Game</h3><div>Exchange: ${x.exchange}</div><div>Awakened: ${x.awakening??'—'}</div></div><div class="report-box"><h3>Health by Entry</h3>${Object.entries(x.healthByEntry).map(([k,v])=>`<div>${k}: ${v??'—'}</div>`).join('')}</div><div class="report-box"><h3>Routes</h3><div>Force: ${x.routes.force}</div><div>Adapt: ${x.routes.adapt}</div><div>Overrun: ${x.routes.overrun}</div></div><div class="report-box"><h3>Pressure</h3><div>Strikes: ${x.strikes}</div><div>Wave Breaches: ${x.wavesBreached}</div><div>Evolutions: ${x.evolutions}</div></div></div><div class="modal-actions"><button id="copyEnd" class="secondary">Copy Log</button><button id="json">Download JSON</button><button id="again">New Game</button></div>`);$('#copyEnd').onclick=copyLog;$('#json').onclick=downloadJSON;$('#again').onclick=()=>FVK.App.newGame()}
function copyLog(){let s=E.getState(),txt=s.log.map(e=>`E${e.exchange} [${e.type}] ${e.message}`).join('\n');navigator.clipboard?.writeText(txt)}
function downloadJSON(){let blob=new Blob([E.exportJSON()],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='fvk-'+E.getState().seed+'.json';a.click();URL.revokeObjectURL(a.href)}
function renderDev(s){$('#devControls').innerHTML=`<label>Seed <input id="seedInput" value="${esc(s.seed)}"></label><label>Kaiju Health <input id="hp" type="number" min="0" max="4" value="${s.kaiju.health??4}"></label><label>Kaiju Location <select id="kl">${E.L.map(x=>`<option value="${x}" ${s.kaiju.location===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Washington Location <select id="wl">${E.L.filter(x=>x!=='approach').map(x=>`<option value="${x}" ${s.washington.location===x?'selected':''}>${x}</option>`).join('')}</select></label><div class="dev-actions"><button id="apply">Apply State</button><button id="wave">Add Wave</button><button id="replay">Replay Seed</button><button id="jdev">JSON</button></div><hr><div class="eyebrow">NEW GAME VALUES</div>${cfg('Kaiju HP','kaijuHealth',FVK.CONFIG.kaijuHealth)}${cfg('Kaiju Start Hand','kaijuStartingHand',FVK.CONFIG.kaijuStartingHand)}${cfg('Kaiju Hand Limit','kaijuHandLimit',FVK.CONFIG.kaijuHandLimit)}${cfg('Washington Start Hand','washingtonStartingHand',FVK.CONFIG.washingtonStartingHand)}${cfg('Washington Hand Limit','washingtonHandLimit',FVK.CONFIG.washingtonHandLimit)}${cfg('Washington Actions','washingtonActions',FVK.CONFIG.washingtonActions)}<button id="savecfg">Save Values + New Game</button>`;$('#apply').onclick=()=>{E.debug('health',{value:$('#hp').value});E.debug('kaijuLocation',{value:$('#kl').value});E.debug('washingtonLocation',{value:$('#wl').value})};$('#wave').onclick=()=>E.debug('addWave');$('#replay').onclick=()=>FVK.App.newGame($('#seedInput').value);$('#jdev').onclick=downloadJSON;$('#savecfg').onclick=()=>{document.querySelectorAll('[data-cfg]').forEach(i=>FVK.CONFIG[i.dataset.cfg]=+i.value);FVK.App.newGame()}}
function cfg(l,k,v){return`<label>${l}<input data-cfg="${k}" type="number" value="${v}"></label>`}
return{init,render,copyLog,downloadJSON}
})();